"""Centralized string constants."""

CONFIG_DIR = "configs"
CONFIG_EXT = ".json"
ZIP_EXT = ".zip"
SQL_EXT = ".sql"

REQUIRED_CONFIG_KEYS = frozenset({"host", "port", "user", "password", "database"})

DEFAULT_BATCH_SIZE = 1000

TIMESTAMP_FORMAT = "%Y%m%d_%H%M%S"

SQL_HEADER = """\
-- SQL Backup generated by sqlbackup
-- Database: {database}
-- Date: {date}

SET @OLD_SQL_MODE=@@SQL_MODE;
SET sql_mode = '';
SET FOREIGN_KEY_CHECKS = 0;

"""

SQL_FOOTER = """
SET FOREIGN_KEY_CHECKS = 1;
SET sql_mode = @OLD_SQL_MODE;
"""

SQL_DROP_TABLE = "DROP TABLE IF EXISTS `{table}`;\n"
SQL_DELIMITER = ";\n\n"

ERR_CONFIG_NOT_FOUND = "Config file not found: {path}"
ERR_CONFIG_INVALID_JSON = "Invalid JSON in config file: {path}"
ERR_CONFIG_MISSING_KEYS = "Missing required keys in config: {keys}"
ERR_BACKUP_PATH_EXISTS = "Backup file already exists: {path}. Use a different path."
ERR_PUSH_FILE_NOT_FOUND = "SQL file not found: {path}"
ERR_CONNECTION_FAILED = "Failed to connect to database: {error}"
ERR_MUTUALLY_EXCLUSIVE = "Must specify either --backup or --push, not both."
ERR_NO_ACTION = "Must specify --backup or --push."
ERR_ZIP_REQUIRES_BACKUP = "--zip can only be used with --backup, or with --execute --backup-path."
ERR_PUSH_ZIP_NO_SQL = "No .sql file found inside zip: {path}"
ERR_PUSH_ZIP_MULTIPLE_SQL = "Multiple .sql files inside zip (ambiguous): {path}"
ERR_PUSH_TARGET_NOT_EMPTY = (
    "Target database '{db}' is not empty ({count} tables). Use --force to overwrite."
)
ERR_COPY_REQUIRES_SOURCE_TARGET = "--copy requires --source and --target."
ERR_COPY_REJECTS_CONFIG_PATH = "--copy does not accept --config or --path."
ERR_INCLUDE_EXCLUDE_MUTUAL = "--include-table and --exclude-table are mutually exclusive."
ERR_INCLUDE_MISSING_TABLES = "Tables not found in source DB: {tables}"
ERR_FILTERS_REQUIRE_BACKUP_OR_COPY = (
    "--include-table and --exclude-table can only be used with --backup or --copy."
)
ERR_FORCE_REQUIRES_PUSH_OR_COPY = "--force can only be used with --push or --copy."
ERR_EXECUTE_FILE_NOT_FOUND = "SQL file not found: {path}"
ERR_EXECUTE_EMPTY = "No executable SQL statements found in: {path}"
ERR_EXECUTE_DELIMITER_UNSUPPORTED = (
    "Custom DELIMITER blocks (stored procedures/triggers) are not supported: {path}"
)
ERR_EXECUTE_UNTERMINATED = (
    "File ends mid-statement (unterminated ';' or string literal); last statement would be "
    "skipped: {path}"
)
ERR_DRY_RUN_REQUIRES_EXECUTE = "--dry-run can only be used with --execute."
ERR_EXECUTE_PATH_NOT_FOUND = "Path not found: {path}"
ERR_EXECUTE_NO_SQL_IN_FOLDER = "No .sql files found in folder: {path}"
ERR_BACKUP_PATH_REQUIRES_EXECUTE = "--backup-path can only be used with --execute."
ERR_YES_REQUIRES_EXECUTE = "--yes can only be used with --execute."
ERR_INCREMENTAL_REQUIRES_BACKUP_PATH = (
    "--incremental with --execute requires --backup-path (nothing to keep otherwise)."
)
