"""Centralized string constants."""

CONFIG_DIR = "configs"
CONFIG_EXT = ".json"

REQUIRED_CONFIG_KEYS = frozenset({"host", "port", "user", "password", "database"})

DEFAULT_BATCH_SIZE = 1000

TIMESTAMP_FORMAT = "%Y%m%d_%H%M%S"

SQL_HEADER = """\
-- SQL Backup generated by sqlbackup
-- Database: {database}
-- Date: {date}

SET FOREIGN_KEY_CHECKS = 0;

"""

SQL_FOOTER = """
SET FOREIGN_KEY_CHECKS = 1;
"""

SQL_DROP_TABLE = "DROP TABLE IF EXISTS `{table}`;\n"
SQL_DELIMITER = ";\n\n"

ERR_CONFIG_NOT_FOUND = "Config file not found: {path}"
ERR_CONFIG_INVALID_JSON = "Invalid JSON in config file: {path}"
ERR_CONFIG_MISSING_KEYS = "Missing required keys in config: {keys}"
ERR_BACKUP_PATH_EXISTS = "Backup file already exists: {path}. Use a different path."
ERR_PUSH_FILE_NOT_FOUND = "SQL file not found: {path}"
ERR_CONNECTION_FAILED = "Failed to connect to database: {error}"
ERR_MUTUALLY_EXCLUSIVE = "Must specify either --backup or --push, not both."
ERR_NO_ACTION = "Must specify --backup or --push."
